API = 'prod-api.kosetto.com'
AUTHORIZATION_TOKEN = 'PASTE_YOUR_FRIEND_TECH_AUTHORIZATION_TOKEN_HERE'
DISCORD_BOT_TOKEN = 'PASTE_YOUR_DISCORD_BOT_TOKEN_HERE'
TARGET_CHANNEL_ID = PASTE_YOUR_DISCORD_CHANNEL_ID_HERE
